config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users
  root to: "posts#index"
  Rails.application.routes.draw do
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :tags, only: [:index]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
  resources :labos, only: [:new]
  resources :news, only: [:new]
  resources :follows, only: [:show]
  resources :followers, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '中学1年生' },
    { id: 3, name: '中学2年生' },
    { id: 4, name: '中学3年生' },
    { id: 5, name: '高校1年生' },
    { id: 6, name: '高校2年生' },
    { id: 7, name: '高校3年生' },
    { id: 8, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord 

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :title
    validates :text
  end

  def self.search(search)
    if search != ""
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/posts_tag.rb
class PostsTag

  include ActiveModel::Model
  attr_accessor :title, :text, :image, :subject_id, :user_id

  with_options presence: true do
    validates :title
    validates :text
    validates :subject_id
  end

  def save
    post = Post.create(title: title, text: text, image: image, user_id: user_id)
    tag = Tag.where(subject_id: subject_id).first_or_initialize
    tag.save

    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/subject.rb
class Subject < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '国語' },
    { id: 3, name: '数学' },
    { id: 4, name: '英語' },
    { id: 5, name: '理科' },
    { id: 6, name: '社会' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations
  has_many :posts, through: :post_tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :subject

  validates :subject_id, numericality: { other_than: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :grade

  with_options presence: true do
    validates :nickname, length: { maximum: 6 }
    validates :grade_id, numericality: { other_than: 1 }
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥々]/ }
    validates :email
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/labos_helper.rb
module LabosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
  <div class="new-header">
    <%= link_to "Academiclabo", "/", class: :logo%>
  </div>
  <div class="user-main">
    <div class="follow-form">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <%= render partial: 'relationships/follow_button', user: @user, class: :follow_button %>
    </div>
    <table class="table">
      <tbody>
        <tr>
          <th class="table_col1">ニックネーム</th>
          <td class="table_col2"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="table_col1">学年</th>
          <td class="table_col2"><%= @user.grade.name %></td>
        </tr>
        <tr>
          <th class="table_col1"><%= link_to "フォロー", follow_path, class: :follow_link %></th>
          <td class="table_col2">
            <%= link_to "#{@user.following_ids.count}人", follow_path, class: :follow_link %>
          </td>
        </tr>
        <tr>
          <th class="table_col1"><%= link_to "フォロワー", follow_path, class: :follow_link %></th>
          <td class="table_col2">
            <%= link_to "#{@user.follower_ids.count}人", follower_path, class: :follower_link %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="center-box">
      <h2 class="center-title"><%= "#{@user.nickname}さんの投稿" %></h2>
      <div class="cols">
        <%= render partial: 'posts/post', collection: @user.posts %>
      </div>
    </div>
  </div>
</div>