config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users
  root to: "posts#index"
  Rails.application.routes.draw do
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :tags, only: [:index]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
  resources :labos, only: [:new]
  resources :news, only: [:new]
  resources :follows, only: [:show]
  resources :followers, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '中学1年生' },
    { id: 3, name: '中学2年生' },
    { id: 4, name: '中学3年生' },
    { id: 5, name: '高校1年生' },
    { id: 6, name: '高校2年生' },
    { id: 7, name: '高校3年生' },
    { id: 8, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord 

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :title
    validates :text
  end

  def self.search(search)
    if search != ""
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/posts_tag.rb
class PostsTag

  include ActiveModel::Model
  attr_accessor :title, :text, :image, :subject_id, :user_id

  with_options presence: true do
    validates :title
    validates :text
    validates :subject_id
  end

  def save
    post = Post.create(title: title, text: text, image: image, user_id: user_id)
    tag = Tag.where(subject_id: subject_id).first_or_initialize
    tag.save

    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/subject.rb
class Subject < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '国語' },
    { id: 3, name: '数学' },
    { id: 4, name: '英語' },
    { id: 5, name: '理科' },
    { id: 6, name: '社会' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations
  has_many :posts, through: :post_tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :subject

  validates :subject_id, numericality: { other_than: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :grade

  with_options presence: true do
    validates :nickname, length: { maximum: 6 }
    validates :grade_id, numericality: { other_than: 1 }
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥々]/ }
    validates :email
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/labos_helper.rb
module LabosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academiclabo</title>
    <meta name="description" content="Academiclaboは学問を通して人と人を結ぶことを目的として2021年3月に作られました。ユーザーの皆様がAcademiclaboを通してさらにご活躍されることを心からお祈り申し上げます。">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" >
  <div class="left-footer">
    <%= link_to "機能紹介", new_labo_path, class: :labo_show %>
  </div>
  <div class="center-footer">
    <%= link_to "Academiclabo", "/", class: :footer_logo%>
  </div>
  <div class="right-footer">
    <%= link_to "お知らせ", new_news_path, class: :contact %>
  </div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='top-contents'>
    <%= link_to "Academiclabo", "/", class: :logo%>
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <li class="user-nickname"><%= link_to current_user.nickname, user_path(current_user), class: "user_nickname" %></li>
          <li class="user-logout"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "user_logout" %></li>
        <% else %>
          <li class="user-login"><%= link_to 'ログイン', new_user_session_path, class: "user_login" %></li>
          <li class="user-sign-up"><%= link_to '新規登録', new_user_registration_path, class: "user_sign-up" %></li>
        <% end %>
      </ul>
  </div>
  <div class="search-content">
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :title, placeholder: "キーワードから検索する", class: "input-box" %>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    <%end%>
  </div>
</header>