config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users
  root to: "posts#index"
  Rails.application.routes.draw do
    resources :relationships, only: [:create, :destroy]
  end
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :tags, only: [:index]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
  resources :labos, only: [:new]
  resources :news, only: [:new]
  resources :follows, only: [:show]
  resources :followers, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/grade.rb
class Grade < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '中学1年生' },
    { id: 3, name: '中学2年生' },
    { id: 4, name: '中学3年生' },
    { id: 5, name: '高校1年生' },
    { id: 6, name: '高校2年生' },
    { id: 7, name: '高校3年生' },
    { id: 8, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord 

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :title
    validates :text
  end

  def self.search(search)
    if search != ""
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/posts_tag.rb
class PostsTag

  include ActiveModel::Model
  attr_accessor :title, :text, :image, :subject_id, :user_id

  with_options presence: true do
    validates :title
    validates :text
    validates :subject_id
  end

  def save
    post = Post.create(title: title, text: text, image: image, user_id: user_id)
    tag = Tag.where(subject_id: subject_id).first_or_initialize
    tag.save

    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/subject.rb
class Subject < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '国語' },
    { id: 3, name: '数学' },
    { id: 4, name: '英語' },
    { id: 5, name: '理科' },
    { id: 6, name: '社会' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations
  has_many :posts, through: :post_tag_relations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :subject

  validates :subject_id, numericality: { other_than: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :grade

  with_options presence: true do
    validates :nickname, length: { maximum: 6 }
    validates :grade_id, numericality: { other_than: 1 }
    validates :name, format: { with: /\A[ぁ-んァ-ン一-龥々]/ }
    validates :email
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create, :search]
  before_action :authenticate_user!, except: [:index]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order('created_at DESC').page(params[:page]).per(10)
    @tags = Tag.all.order('subject_id ASC')
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
  end

  def new
    @post = PostsTag.new
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
    @like = Like.new
  end

  def create
    @post = PostsTag.new(post_params)
    if @post.valid? 
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @post.update(post_edit_params)
    if @post.save
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def search
    @posts = Post.search(params[:title]).order('created_at DESC')
    @tags = Tag.all.order('subject_id ASC')
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @post.user
  end

  def post_params
    params.require(:posts_tag).permit(:title, :text, :image, :subject_id).merge(user_id: current_user.id)
  end

  def post_edit_params
    params.require(:post).permit(:title, :text, :image)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/labos_helper.rb
module LabosHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_post.html.erb
<div class="card" ontouchstart="this.classList.toggle('hover');">
  <div class="user-form">
    <%= link_to "#{post.user.nickname}", user_path(post.user), class: :card_user %>
  </div>
  <%= link_to post.title, post_path(post), class: :card_show %>
</div>

app/views/posts/edit.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
    <div class="new-header">
      <%= link_to "Academiclabo", "/", class: :logo%>
    </div>
    <div class="posts-main">
      <%= form_with model: @post, local: true do |f| %>
        <h2 class="new-top">変更情報を入力</h2>
        <%= render 'shared/error_messages', model: f.object %>
        <div class="new-posts">
          <div class="items-explain">
            <div class="weight-bold-text">
              タイトルを記入してください(必須)
            </div>
            <div class="post-field">
              <%= f.text_area :title, class:"posts-title", id:"post-info", placeholder:"タイトル" %>
            </div>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              投稿文を記入してください(必須)
            </div>
            <div class="post-field">
              <%= f.text_area :text, class:"posts-text", id:"post-info", placeholder:"投稿文" %>
            </div>
          </div>
        </div>
        <div class="img-upload">
          <div class="img-upload">
            <div class="weight-bold-text">
              投稿画像を選択してください
            </div>
            <label class="file-form">
              ファイルを選択
              <%= f.file_field :image, id:"post-image", class: :file_input %>
            </label>
          </div>
        </div>
        <div class="post-btn-contents">
          <%= f.submit "更新する" ,class:"post-create-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
  <%= render "shared/header" %>
  <div class="band">
    <div id="particles">
      <div class="overlay"></div>
      <div id="intro">
        <h1 class="intro-message1">WELCOME TO<br>ACADEMICLABO</h1>
        <p class="intro-message2">〜学問を通して人と人を繋ぐ〜</p>
      </div>
    </div>
  </div>
  <h1 class="produce-main-title">Academiclaboの使い方</h1>
  <div class="produce-box">
    <div class="produce">
      <h2 class="produce-title">STEP1</h2>
      <%= image_tag "スクリーンショット 2021-04-06 17.43.58.png", class:"produce-image" %>
      <p class="produce-message">最初に新規登録/ログインをする</p>
    </div>
    <div class="produce">
      <h2 class="produce-title">STEP2</h2>
      <%= image_tag "スクリーンショット 2021-04-06 17.44.30.png", class:"produce-image" %>
      <p class="produce-message">次に投稿する</p>
    </div>
    <div class="produce">
      <h2 class="produce-title">STEP3</h2>
      <%= image_tag "スクリーンショット 2021-04-08 19.15.42.png", class:"produce-image" %>
      <p class="produce-message">最後にコメントしてもらう</p>
    </div>
  </div>
  <div class='main'>
    <div class="left-box">
      <div class="lank">
        <h1 class="lank-title">POPULAR POSTS</h1>
        <%@all_ranks.each do |post| %>
          <div class="lank-link">
            <div class="lank-form">
              <%= link_to post.user.nickname, user_path(post.user), class: "lank_user"%>
            </div>
            <%= link_to post.title, post_path(post), class: "lank_link" %>
          </div>
        <%end%>
      </div>
    </div>
    <div class="center-box">
      <h2 class="center-title">NEW POSTS</h2>
      <div class="cards">
        <%= render partial: 'post', collection: @posts %>
      </div>
      <%= paginate @posts %> 
    </div>
    <div class="right-box">
      <div class="subject">
        <h1 class="subject-title">SUBJECT</h1>
        <%@tags.each do |tag| %>
            <p class="subject-link"><%= link_to tag.subject.name, post_tags_path(tag), class: "subject_link" %></p>
        <%end%>
      </div>
    </div>
    <div>
      <%= link_to(new_post_path, class: 'post-btn') do %>
        <span class='post-btn-text'>投稿する</span>
        <%= image_tag 'pencil.png' , size: '185x50' ,class: "post-btn-icon" %>
      <% end %>
    </div>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/posts/new.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
    <div class="new-header">
      <%= link_to "Academiclabo", "/", class: :second_logo%>
    </div>
    <div class="posts-main">
      <%= form_with model: @post, url: posts_path, local: true do |f| %>
        <h2 class="new-top">新規投稿の情報を入力</h2>
        <%= render 'shared/error_messages', model: f.object %>
        <div class="new-posts">
          <div class="items-explain">
            <div class="weight-bold-text">
              タイトルを記入してください(必須)
            </div>
            <div class="post-field">
              <%= f.text_area :title, class:"posts-title", id:"post-info", placeholder:"タイトル" %>
            </div>
          </div>
          <div class="items-explain">
            <div class="weight-bold-text">
              投稿文を記入してください(必須)
            </div>
            <div class="post-field">
              <%= f.text_area :text, class:"posts-text", id:"post-info", placeholder:"投稿文" %>
            </div>
          </div>
        </div>
        <div class="img-upload">
          <div class="weight-bold-text">
            投稿画像を選択してください
          </div>
          <label class="file-form">
            ファイルを選択
            <%= f.file_field :image, id:"post-image", class: :file_input %>
          </label>
        </div>
        <div class="psot-detail">
          <div class="grade-form">
            <div class="weight-bold-text">
              科目を選択してください(必須)
            </div>
            <%= f.collection_select(:subject_id, Subject.all, :id, :name, {}, {class:"grade-select"}) %>
          </div>
        </div>
        <div class="post-btn-contents">
          <%= f.submit "投稿する" ,class:"post-create-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
  <div class="header">
    <div class="new-header">
      <%= link_to "Academiclabo", "/", class: :logo%>
    </div>
    <div class="search-content">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :title, placeholder: "キーワードから検索する", class: "input-box" %>
        <button class="search-button">
          <%= image_tag "search.png", class:"search-icon" %>
        </button>
      <% end %>
    </div>
  </div>
  <div class="main">
    <div class="left-box">
    </div>
    <div class="center-box">
      <div class="contents row">
        <% @posts.each do |post| %>
          <%= render partial: 'post', collection: @posts %>
        <% end %>
      </div>
    </div>
    <div class="right-box">
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="body">
  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>
  <div class="content">
  <div class="new-header">
    <%= link_to "Academiclabo", "/", class: :logo%>
  </div>
  <main class="main">
    <div class="show-inner">
      <div class="show_wrapper">
        <div class="show-user">
          <p>by</p>
          <%= link_to "#{@post.user.nickname}", user_path(@post.user), class: :show_user %>
        </div>
        <% if current_user == @post.user%>
          <div class="post_manage">
            <%= link_to "Edit", edit_post_path(@post), method: :get, class: "post-edit-btn" %>
            <%= link_to "Delete", post_path(@post), method: :delete, class:"post-destroy-btn" %>
          </div>
        <% end %>
        <div class="good-form">
          <h3 class="good-count">いいね件数:<%= @post.likes.count %></h3>
          <% if current_user.already_liked?(@post) %>
            <%= button_to 'cancel', post_like_path(@post), method: :delete, class: "good-btn" %>
          <% else %>
            <%= button_to ' good ', post_likes_path(@post), class: "good-btn" %>
          <% end %>
        </div>
        <div class="show-form">
          <div class="post_title">
            <p class="detail_title">
              <%= @post.title%>
            </p>
          </div>
          <div class="post_image">
            <% if @post.image.present? %>
              <div class="image-form">
                <%= image_tag @post.image, class: "show-image" %>
              </div>
            <% end %>
          </div>
          <div class="post_body">
            <div class="post_detail">
              <div class="message-form">
                <p class="detail_message">
                  <%= @post.text %>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="post_comments">
          <%= form_with model: [@post, @comment], local: true do |f|%>
            <div class="comment-form">
              <div class="field">
                <%= f.label :text, "コメント", class:"comment-title" %><br />
                <%= f.text_area :text, class:"comment-field" %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :post_comment_btn  %>
              </div>
            </div>
          <% end %> 
          <ul class="comments_lists">
            <p class="cindex-title">コメント一覧</p>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <div class="comment-user">
                  <%= link_to "#{comment.user.nickname}", user_path(@post.user), class: :comment_user %>
                  <p class="comment-message">さんのコメント</p>
                </div>
                <%= comment.text %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </main>
</div>